version: '2'
services:
    bolg-app:
        image: bolg
        external_links:
            - bolg-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=bolg
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bolg-mongodb:
        extends:
            file: mongodb.yml
            service: bolg-mongodb
