version: '2'
services:
    bolg-mongodb:
        container_name: bolg-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb bolg-mongodb-config
    bolg-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    bolg-mongodb-config:
        image: mongo:3.3.5
        container_name: bolg-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
